### ISSUE TITLE
How to recover categories by sorting by "position"

### ISSUE THREAD

**Issue by JohnDoIt** [sonata-project/SonataClassificationBundle#100]
I would like to do in a CategoryController : 

    $categories = $this->container->get('sonata.classification.manager.category')->getCategories('ORDER BY position');

The goal is to display in the view, the categories sorted by position. 
Because I don't understand in admin / sonata / classification / category / create, the role of field position, I tried to change the order but in my view nothing is sorted.

But I don't know how to do this. Override CategoryManager ? I tried to do : 

(In loadCategories())

    /**
     * Load all categories from the database, the current method is very efficient for < 256 categories
     *
     */
    protected function loadCategories()
    {
      ...

        $categories = $this->getObjectManager()->createQuery(sprintf('SELECT c FROM %s c INDEX BY c.id ORDER BY position', $class))
            ->execute();

    ...

and the ORDER BY position work. In my view, my categories are sorted. 
Thanks.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
