### ISSUE TITLE
Unable to create new Context from Admin

### ISSUE THREAD

**Issue by jerome-fix** [sonata-project/SonataClassificationBundle#106]

**Comment by jerome-fix** [comment]
"Entity of type Application\Sonata\ClassificationBundle\Entity\Context is missing an assigned ID for field 'id'. The identifier generation strategy for this entity requires the ID field to be populated before EntityManager#persist() is called. If you want automatically generated identifiers instead you need to adjust the metadata mapping accordingly."

I have :
"sonata-project/admin-bundle": "~2.4@dev"
"sonata-project/classification-bundle": "~2.3@dev"

**Comment by jerome-fix** [comment]
I don't undestand this commit : https://github.com/sonata-project/SonataClassificationBundle/commit/3403dc9cc008ad947bf1b965949841924b7e7d84.
Why hide the field ID ?

If I remove the `ifTrue()…ifEnd` part everything seems ok.

**Comment by pborreli** [comment]
having same issue

**Comment by NeuralClone** [comment]
I'm having the exact same problem. It causes the creation of new contexts to fail. Contexts can be manually added to the database and everything seems to work once that's done (including editing) but that defeats the entire purpose the AdminBundle...

The commit referenced above by @jerome-fix ( 3403dc9cc008ad947bf1b965949841924b7e7d84 )  doesn't make any sense. "If the object doesn't exist, hide the field that allows it to be created." Also, `false === null` makes even less sense as a logical test. That will always evaluate to `false`.

**Comment by ppetermann** [comment]
I'm having the same problem.

also i looked into the code (and jeromes fix), I think i got what was intended here, and put a suggestion for a fix in a comment here: https://github.com/sonata-project/SonataClassificationBundle/commit/3403dc9cc008ad947bf1b965949841924b7e7d84
