### ISSUE TITLE
fetching parent_id from category fails

### ISSUE THREAD

**Issue by ferriss** [sonata-project/SonataClassificationBundle#117]
I'm trying to get all category content to sort the results yielding a readable category tree but somehow the parent_id does not come with the data.
Is this a bug or meant to be?
parent_id can be queried but to fetch all descendants this is useless...

$em = $this->modelManager->getEntityManager('Application\Sonata\ClassificationBundle\Entity\Category');
		$qb = $em->createQueryBuilder();
		$qb = $qb->add('select', 'u')
				->add('from', 'Application\Sonata\ClassificationBundle\Entity\Category u');
		$query = $qb->getQuery();

Perhaps I should use another category entity which supports tree building...

**Comment by ferriss** [comment]
After installing the updated bundle some problems are gone and structure view is available.
An improvement!

**Comment by core23** [comment]
Is this issue fixed with the latest version?

**Comment by ferriss** [comment]
it's fixed yes, works like a charm!
