### ISSUE TITLE
How to extend Tag and Category entities to make ManyToOne relationship?

### ISSUE THREAD

**Issue by edouardkombo** [sonata-project/SonataClassificationBundle#121]
Hi everyone,

I'm using the ClassificationBundle "^2.2" version.

What I want to do is to make a ManyToOne relationship between tags and categories, but I have no result in mapping, and it is very bizarre.

So, I have extended my Tag and Category entities like this:

Tag entity

	<?php

	/**
	 * This file is part of the <name> project.
	 *
	 * (c) <yourname> <youremail>
	 *
	 * For the full copyright and license information, please view the LICENSE
	 * file that was distributed with this source code.
	 */

	namespace Application\Sonata\ClassificationBundle\Entity;

	use Sonata\ClassificationBundle\Entity\BaseTag as BaseTag;
	use Doctrine\ORM\Mapping as ORM;

	/**
	 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
	 *
	 * References :
	 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
	 *
	 * @author <yourname> <youremail>
	 */
	class Tag extends BaseTag
	{
		/**
		 * @var integer $id
		 */
		protected $id;

		/**
		 * @ORM\ManyToOne(targetEntity="\Application\Sonata\ClassificationBundle\Entity\Category", inversedBy="tags")
		 * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
		 */
		protected $categories;

		/**
		 * Get id
		 *
		 * @return integer $id
		 */
		public function getId()
		{
			return $this->id;
		}

		/**
		 * Add tags
		 *
		 * @param \Application\Sonata\ClassificationBundle\Entity\Category $category
		 */
		public function addCategories(\Application\Sonata\ClassificationBundle\Entity\Category $category)
		{
			$this->categories[] = $category;
		}

		/**
		 * Get tags
		 *
		 * @return \Doctrine\Common\Collections\Collection
		 */
		public function getCategories()
		{
			return $this->categories;
		}
	}

Category entity

	<?php

	/**
	 * This file is part of the <name> project.
	 *
	 * (c) <yourname> <youremail>
	 *
	 * For the full copyright and license information, please view the LICENSE
	 * file that was distributed with this source code.
	 */

	namespace Application\Sonata\ClassificationBundle\Entity;

	use Sonata\ClassificationBundle\Entity\BaseCategory as BaseCategory;
	use Doctrine\ORM\Mapping as ORM;

	/**
	 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
	 *
	 * References :
	 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
	 *
	 * @author <yourname> <youremail>
	 */
	class Category extends BaseCategory
	{
		/**
		 * @var integer $id
		 */
		protected $id;

		/**
		 * @ORM\OneToMany(targetEntity="\Application\Sonata\ClassificationBundle\Entity\Tag", mappedBy="categories")
		 */
		protected $tags;

		/**
		 * Get id
		 *
		 * @return integer $id
		 */
		public function getId()
		{
			return $this->id;
		}

		/**
		 * Add tags
		 *
		 * @param \Application\Sonata\ClassificationBundle\Entity\Tag $tag
		 */
		public function addTags(\Application\Sonata\ClassificationBundle\Entity\Tag $tag)
		{
			$this->tags[] = $tag;
		}

		/**
		 * Get tags
		 *
		 * @return \Doctrine\Common\Collections\Collection
		 */
		public function getTags()
		{
			return $this->tags;
		}
	}

When I try to execute: app/console doctrine:schema:update --dump-sql

I have this message

    Nothing to update - your database is already in sync with the current entity metadata.

Any information to solve this problem please?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
