### ISSUE TITLE
no way to override validation.xml

### ISSUE THREAD

**Issue by pirasterize** [sonata-project/SonataClassificationBundle#131]
I need to increase the max length of the category name and I just copied and modified for my needs validation.xml in Application\Sonata\ClassificationBundle\Resources\config\
but no way to make it work... (already tried with clear cache)
Don't know if is a bug or what ?!

The error is always about 32 chars max length (the default in vendor/.../validation.xml)

Here is my version of validation.xml

```
 <?xml version="1.0" ?>
 <constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping
    http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">


<class name="Application\Sonata\ClassificationBundle\Entity\Category">

    <property name="name">
        <constraint name="NotBlank" />
        <constraint name="NotNull" />
        <constraint name="Length">
            <option name="min">2</option>
            <option name="max">64</option>
        </constraint>
    </property>

</class>
```

</constraint-mapping>

Thanks for any answer

**Comment by Soullivaneuh** [comment]
Please try to clear all the cache and try again.

**Comment by pirasterize** [comment]
Thanks for answer
I already tried many times clearing cache (rm -rf app/cache/*), right now again...

**Comment by tolstoyleo** [comment]
I'm having this exact same issue. it doesn't work with moving the validation.xml file to your own bundle's config, nor does it work by overriding the validate method as stated in the document, my overridden method in my own admin class looks like this:

    $errorElement
            ->with('name')
                ->assertLength(array('max' => 50))
            ->end()
        ;

so now if i submit a text > 32, i get the error that says the value is too long, it should be 32 characters or less. and when it's over 50... i get BOTH ERRORS about 32 chars and 50.

What am i not doing right here?

**Comment by kozmenkoav** [comment]
The same problem. I made category entity translatable, so I don't need **name** field of original entity to be required. How I can remove constraint defined in **validation.xml**?

**Comment by OskarStark** [comment]
Ping @rande

**Comment by Tim4c** [comment]
Have you found any solution ?

**Comment by kozmenkoav** [comment]
No, unfortunately.

**Comment by Tim4c** [comment]
Ok after few hours, i finally found a way to solve the problem... 
I think, it's not the best way (any idea...), because if you need to update the max length value, you have to update two files.

In your CategoryAdmin class
```
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
          ->add('name', null, array(
            'attr' => array(
              'maxlength' => 200
            )
          ))
        ;
    }
    
    public function getFormBuilder() {
        //OverrideCategoryValidation => custom validation group
        $this->formOptions = array('validation_groups' => 'OverrideCategoryValidation');

        $formBuilder = parent::getFormBuilder();
        return $formBuilder;
    }
```
and in your category entity class : 
```
use Symfony\Component\Validator\Constraints as Assert;
    /**
     * @Assert\Length(
     *      min = 2,
     *      max = 200,
     *      groups={"OverrideCategoryValidation"}, 
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    protected $name;
```

**Comment by alebo** [comment]
It's possible to exclude vendor's validation in a compiler pass. Then you can just copy validation.xml to your inherited bundle and maintain it there.

Here's a quick implementation (not tested):

```php
        $validatorBuilder = $container->getDefinition('validator.builder');

        foreach ($validatorBuilder->getMethodCalls('addXmlMappings') as $call) {
            if ('addXmlMappings' == $call[0]) {
                $validatorBuilder->removeMethodCall($call[0]);
                $arguments = array();
                foreach ($call[1][0] as $path) {
                    if (false !== strpos($path, 'sonata-project/classification-bundle/Resources/config/validation.xml')) {
                        continue;
                    }
                    $arguments[]= $path;
                }
                $validatorBuilder->addMethodCall($call[0], array($arguments));

                break;
            }
        }
```

**Comment by Gradius30** [comment]
Hello guys. Have anybody found a way to remove property validation from already defined class? Im solving the same issue as @kozmenkoav - moving Category->name into Translatable...
