### ISSUE TITLE
Can I use SonataTranslationBundle for translate SonataClassificationBundle?

### ISSUE THREAD

**Issue by dvapelnik** [sonata-project/SonataClassificationBundle#132]
Hi! 
I want to translate `SonataClassificationBundle` with `SonataTranslationBundle` but I cant correctly extent the `Category.orm.yml` config using Gedmo additions: I catch error with duplicate configuration for already configured 
```
[Doctrine\ORM\Mapping\MappingException]                                                                                          
  Duplicate definition of column 'name' on entity 'Application\Sonata\ClassificationBundle\Entity\Category' in a field or discrim  
  inator column mapping.
```

Is there a legal way to translate entities from `SonataClassificationBundle` with `SonataTranslationBundle`?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
