### ISSUE TITLE
Multiple category entities

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataClassificationBundle#139]
Currently I have a hard task: I have to implement a site where Products and News are both organized in categories, but Product categories have a few extra fields. For example the product category needs to contain the margin for products under it.

Can I do that right now? If yes, how?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

Please have a look at the ecommerce bundle, there are some extended categories: https://github.com/sonata-project/ecommerce/blob/2.x/src/ProductBundle/Entity/BaseProductCategory.php

**Comment by sagikazarmark** [comment]
Thanks
