### ISSUE TITLE
i think we should remove this comment

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataClassificationBundle#149]
here:
https://github.com/sonata-project/SonataClassificationBundle/blob/master/Resources/views/CategoryAdmin/tree.html.twig#L12-L14

it is used here:
https://github.com/sonata-project/SonataClassificationBundle/blob/master/Controller/CategoryAdminController.php#L101

ping @rande

**Comment by OskarStark** [comment]
Ping @Soullivaneuh

**Comment by Soullivaneuh** [comment]
No using this bundle so I prefer @rande opinion.

**Comment by OskarStark** [comment]
> This template is not used at all, it is just a template

But it is used in the ``CategoryAdminController``

**Comment by OskarStark** [comment]
ping @core23 @greg0ire

**Comment by greg0ire** [comment]
Please check that the comment was introduced before the usage. If yes, then we should remove it. If not, WTF?

**Comment by jordisala1991** [comment]
Introduced in the same commit: https://github.com/sonata-project/SonataClassificationBundle/commit/330a10b49062dad5316b772d56f90f319e356d8c

So, should we remove it?

**Comment by greg0ire** [comment]
> If not, WTF?

I think it really makes no sense, we should remove it IMO.
