### ISSUE TITLE
PostgreSQL issue because order by behave differently

### ISSUE THREAD

**Issue by rlamarche** [sonata-project/SonataClassificationBundle#156]
On branch master.

In CategoryManager, when one or more categories are created (exluding the root category), I the following message : "The first category must be the root" always.

The reason is that PostgreSQL lists null values at the end by defaut.
Tested on Postgres 9.5 from https://hub.docker.com/r/oslandia/pggis/

**Comment by OskarStark** [comment]
could you please provide this commit as a PR here, so that we can test your change?

some tests would be great

Thank you @rlamarche

**Comment by core23** [comment]
Think this could fix your issue https://github.com/sonata-project/SonataClassificationBundle/pull/108

**Comment by rlamarche** [comment]
PR fixed @OskarStark. Sorry for the delay. Thank you @core23, it seems to be a more elegant fix.

**Comment by OskarStark** [comment]
is it fixed now? shall we fix it? don't see a PR

**Comment by rlamarche** [comment]
see #157

**Comment by core23** [comment]
Can we close this @rlamarche ?
