### ISSUE TITLE
How to use classificationBundle in my owner entity and entityAdmin ?

### ISSUE THREAD

**Issue by meddridi** [sonata-project/SonataClassificationBundle#161]

**Comment by meddridi** [comment]
Hi, plz how i can use the bundle in my entity ..!

**Comment by Soullivaneuh** [comment]
All the documentation is here: https://sonata-project.org/bundles/classification/2-2/doc/index.html

Please follow it. If you have a specific question or issue with it, please reopen an another issue with a complete description and use cases.
