### ISSUE TITLE
"Add Category" Fatal Error

### ISSUE THREAD

**Issue by stphnpt** [sonata-project/SonataClassificationBundle#167]
When trying to add a new category from the Admin: 

Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\Extension\Core\Type\ChoiceType::normalizeLegacyChoices() must be of the type array, null given, called in .../vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php on line 266 and defined

**Comment by core23** [comment]
This issue should be fixed in the latest stable / master version. Please have a look at the docs too.

If this is still present, feel free to reopen this issue
