### ISSUE TITLE
[DOCS] Custom implementation

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataClassificationBundle#170]
There are no docs, how to use a category in a custom admin or form.

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataClassificationBundle/issues/162

**Comment by OskarStark** [comment]
refs the same ticket? @core23

**Comment by core23** [comment]
Maybe we can create docs after finding a solution for this: https://github.com/sonata-project/SonataBlockBundle/issues/244

**Comment by VincentLanglet** [comment]
What's the status of this @core23 ? Do you know how to do it ? Can you write doc about it ?

This issue is 5 year old without activities. I think we should follow the stale-bot strategy and close it if no-one wants to work on it.

**Comment by core23** [comment]
As no one else is asking for a guidance for this component, we could close this.
