### ISSUE TITLE
Problem with SonataClassificationBundle.fr.xliff

### ISSUE THREAD

**Issue by GuillaumeBalazy** [sonata-project/SonataClassificationBundle#171]
In this f025c64ae87354b1ab8ca02515cc513ee424df9a there are twice "breadcrumb.link_category_tree"

> An exception has been thrown during the rendering of a template ("Invalid resource provided: "1.2"; Errors: [ERROR 1877] Element '{urn:oasis:names:tc:xliff:document:1.2}trans-unit': Duplicate key-sequence ['breadcrumb.link_category_tree'] in key identity-constraint '{urn:oasis:names:tc:xliff:document:1.2}K_unit_id'.

**Comment by xavierlacot** [comment]
The [merge of the last commit](https://github.com/sonata-project/SonataClassificationBundle/pull/133) duplicated the key `link_category_tree` (and the Travis tests reported it). Please revert https://github.com/sonata-project/SonataClassificationBundle/pull/133

**Comment by GuillaumeBalazy** [comment]
Thanks!
