### ISSUE TITLE
Composer inconsistencies regarding ClassificationBundle

### ISSUE THREAD

**Issue by lemorragia** [sonata-project/SonataClassificationBundle#185]
Hi there,

don't know if it is a bug, or an unexpected behaviour, and i'm not sure that the issue list the right way to report it. Anyway, i think that at least is useful to mention it: i use classificationBundle in a bunch of project, using the context service and some other stuff. So i'm using it in an environment checking out a specific commit of ClassificationBundle (i do this for a couple of other bundles too, mainly for bug-fixing). Now, the last update in the composer.json leaves me in an inconsistent state: 
composer has an "un-implementable" feature, i discovered
https://github.com/composer/composer/issues/3705
https://github.com/composer/composer/issues/599

So when you checkout a specific commit, it always uses the requirements from the last commit(in this case, with all the 3.0 versions). In this case, they are incompatible (mainly because, that i know it, composer lets you checkout a specific commit referencing only the dev-master branch, like dev-master#xyzcommit)

I was hoping to find some help here, the way i see it i've got some solutions:
-get an older version, hoping that no bugs come back and rewrite a great bunch of code
-update to the 3.0 branch, but i think it is a work-in-progress and not ready for a production environment
-maybe forking the latest 2.2 branch and merge it with the add_context branch is a viable solution? But maybe there's a reason the branch was not merged in the 2.2 in the first place...
-other? is there a documentation page with some version-compatibility of the various bundles at the most recent state? i'm having a hard time fixing all the sonata-bundles requirements so that an update can be done and at the same time knowing what are the most-recent stable versions..

**Comment by greg0ire** [comment]
>  -update to the 3.0 branch, but i think it is a work-in-progress and not ready for a production environment

The 3.0 is coming soon, so it might be your best option. And by the way, you seem worried by it not being "ready for a prod environement", but doesn't the `dev` in `dev-master` ring a bell?

**Comment by lemorragia** [comment]
yes, it does...i don't understand if you are referring to the fact that i'm pulling explicit commits (in which case using the "dev-master#commit" syntax is the only way, that i know of, to do it), or that i'm using the dev-master branch not knowing that is a "work-in-progress" branch (in this case i explained myself very badly: i didn't mean that i'm waiting for a long-and-stable version, but in general for a 3.0 version release  with a working set of packages)

anyway, if the 3.0 version is not far away, maybe it is indeed my best option

**Comment by greg0ire** [comment]
I'm referring to the fact that you are using "dev-master", and the name `dev` is short for `development`, so you can't expect it to be "production ready". Only releases are supposed to be used in production.

**Comment by lemorragia** [comment]
yes, i know. Unfortunately, there's no release of this bundle with the context service which i am making use of. I am posting here pointing out two things:
-composer has an unexpected behaviour that some people like me finds odd, and this behaviour is present in the current development branch
-i'm having a hard time with the docs to find out a list of updated sonata releases which can coexist with each other. Often one bug exist in one release and on stackoverflow the reccomended solution is to switch on the dev-master branch, as the bugfix is not merged back into the release. 

and i was seeking for advices

**Comment by greg0ire** [comment]
I know exactly how you feel! Hopefully with the new release process, releases will come far more often, and your problems should go away.

**Comment by lemorragia** [comment]
Just to inform everyone, with the new releases i managed to switch to the 3.x branches and, though a couple of packages don't have a 3.x branch yet, the problem is now solved. If this is the new release process, i like it ;-)

**Comment by Soullivaneuh** [comment]
For more information and keep update about global Sonata management, I suggest you to follow this repository: https://github.com/sonata-project/dev-kit
