### ISSUE TITLE
Add basic implementation of this bundle

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataClassificationBundle#193]
When using this bundle, you _MUST_ use easy-extends to create a basic implementation for this bundle in order to use it.

IMO this is a bad idea, because every project has a dummy `Application\Sonata\ClassificationBundle` bundle with simple entities containing only an `id` property and the corresponding getter.

We should find a way to include these files in the repo and only load them when they are not overwritten by easy-extends.

**Comment by OskarStark** [comment]
we should be able to generate the files to a custom namespace, this should fix the problem, i think the easy extends bundle has some open PR's for this

**Comment by core23** [comment]
Symfony flex solves this issue
