### ISSUE TITLE
The option "cascade_validation" does not exist

### ISSUE THREAD

**Issue by Grazulex** [sonata-project/SonataClassificationBundle#244]
Hello,

When I try to edit/create a new category I have this error 
"The option "cascade_validation" does not exist"

my composer.json is

>     "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.1.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "sonata-project/admin-bundle": "^3.9",
        "jms/di-extra-bundle": "^1.8",
        "jms/translation-bundle": "^1.3",
        "sonata-project/doctrine-orm-admin-bundle": "^3.1",
        "sonata-project/intl-bundle": "^2.2",
        "symfony/security-bundle": "^3.1",
        "sonata-project/media-bundle": "^3.3",
        "sonata-project/classification-bundle": "^3.1"
    },

and the Stack Trace is

> [1] Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: The option "cascade_validation" does not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "horizontal_input_wrapper_class", "horizontal_label_class", "horizontal_label_offset_class", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "label_render", "mapped", "method", "post_max_size_message", "property_path", "required", "sonata_admin", "sonata_field_description", "sonata_help", "translation_domain", "trim", "upload_max_size_message", "validation_groups".
    at n/a
        in C:\wamp\www\ddvinyl\vendor\symfony\symfony\src\Symfony\Component\OptionsResolver\OptionsResolver.php line 685

    at Symfony\Component\OptionsResolver\OptionsResolver->resolve(array('cascade_validation' => true, 'data_class' => 'Application\Sonata\ClassificationBundle\Entity\Category'))
        in C:\wamp\www\ddvinyl\vendor\symfony\symfony\src\Symfony\Component\Form\ResolvedFormType.php line 95

    at Symfony\Component\Form\ResolvedFormType->createBuilder(object(FormFactory), 's5826ddc518bbb', array('cascade_validation' => true, 'data_class' => 'Application\Sonata\ClassificationBundle\Entity\Category'))
        in C:\wamp\www\ddvinyl\vendor\symfony\symfony\src\Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeDataCollectorProxy.php line 81

    at Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeDataCollectorProxy->createBuilder(object(FormFactory), 's5826ddc518bbb', array('cascade_validation' => true, 'data_class' => 'Application\Sonata\ClassificationBundle\Entity\Category'))
        in C:\wamp\www\ddvinyl\vendor\symfony\symfony\src\Symfony\Component\Form\FormFactory.php line 85

    at Symfony\Component\Form\FormFactory->createNamedBuilder('s5826ddc518bbb', 'Symfony\Component\Form\Extension\Core\Type\FormType', null, array('cascade_validation' => true, 'data_class' => 'Application\Sonata\ClassificationBundle\Entity\Category'))
        in C:\wamp\www\ddvinyl\vendor\sonata-project\doctrine-orm-admin-bundle\Builder\FormContractor.php line 92

    at Sonata\DoctrineORMAdminBundle\Builder\FormContractor->getFormBuilder('s5826ddc518bbb', array('cascade_validation' => true, 'data_class' => 'Application\Sonata\ClassificationBundle\Entity\Category'))
        in C:\wamp\www\ddvinyl\var\cache\dev\classes.php line 10456

    at Sonata\AdminBundle\Admin\AbstractAdmin->getFormBuilder()
        in C:\wamp\www\ddvinyl\var\cache\dev\classes.php line 11449

    at Sonata\AdminBundle\Admin\AbstractAdmin->buildForm()
        in C:\wamp\www\ddvinyl\var\cache\dev\classes.php line 10496

    at Sonata\AdminBundle\Admin\AbstractAdmin->getForm()
        in C:\wamp\www\ddvinyl\vendor\sonata-project\admin-bundle\Controller\CRUDController.php line 502

    at Sonata\AdminBundle\Controller\CRUDController->createAction()
        in  line 

    at call_user_func_array(array(object(CategoryAdminController), 'createAction'), array())
        in C:\wamp\www\ddvinyl\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php line 153

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in C:\wamp\www\ddvinyl\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php line 68

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in C:\wamp\www\ddvinyl\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php line 169

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in C:\wamp\www\ddvinyl\web\app_dev.php line 28
`

Can somebody help me ?
thanks

**Comment by core23** [comment]
The option was remove with [symfony 3.0](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#form).

Can you supply a PR with a fix @Grazulex ?

**Comment by gremo** [comment]
This happens also for collections, making the bundle nearly unusable with Symfony 3. Any plan to fix it?

**Comment by greg0ire** [comment]
We would welcome any PR to fix that. If you want to provide one, you should have a look at [this](https://github.com/sonata-project/SonataClassificationBundle/search?utf8=%E2%9C%93&q=cascade_validation), and make it change depending on the symfony version in use.

**Comment by gremo** [comment]
Yep @greg0ire thanks, I'm already aware of where the code should be fixed. I'll look into in a couple of hours. I noticed that SonataCoreBundle uses `Kernel::VERSION`: do you think this is the right way to detect Symfony version?

**Comment by greg0ire** [comment]
>  I noticed that SonataCoreBundle uses Kernel::VERSION: do you think this is the right way to detect Symfony version?

I know for a fact it isn't. Instead, you should try to detect the version of the form component.

**Comment by greg0ire** [comment]
Here is [an example](https://github.com/sonata-project/SonataAdminBundle/blob/240ecbd02d453f9acaf81e00112ff5d8dae4459b/Form/Type/AclMatrixType.php#L39)

**Comment by greg0ire** [comment]
See #250

**Comment by gremo** [comment]
@greg0ire I think that #250 will introduce a different behavior between this bundle and other sonata bundles. When using this bundle with Symfony 2 the `cascade_validation` option would trigger validation of all the nested entities while in Symfony 3 the same won't happen. How about adding the `Valid` constraint to the whole form?

**Comment by gremo** [comment]
For example, this:

```php
/**
 * {@inheritdoc}
 */
public function getFormBuilder()
{
    // // NEXT_MAJOR: remove when dropping Symfony <3 support
    if (!method_exists('Symfony\Component\Form\Abstractype', 'getName')) {
        unset($this->formOptions['cascade_validation']);
        if (!isset($this->formOptions['constraints'])) {
            $this->formOptions['constraints'] = array();
        }

        $this->formOptions['constraints'][] = new Valid();
    }

    return parent::getFormBuilder();
}
```

**Comment by greg0ire** [comment]
Commenting on #250 itself would have been better ;)

> How about adding the Valid constraint to the whole form?

Not sure `Valid` works recursively… its option are `traverse` and `deep`, and apply when dealing with… arrays.

**Comment by greg0ire** [comment]
[The documentation is not crytal clear about this](http://symfony.com/doc/2.3/reference/constraints/Valid.html). Could you test your solution and report back?

**Comment by greg0ire** [comment]
Also, `Valid exists since 2.3`, it would be fine to use it unconditionnaly IMO, like this : 

```
public function getFormBuilder()
{
    $this->formOptions['constraints'][] = new Valid();
    return parent::getFormBuilder();
}

    return parent::getFormBuilder();
}
```

**Comment by gremo** [comment]
@greg0ire I did a quick test with the `CategoryAdmin `and it seems to work fine out of the box. Choosing a parent category which isn't valid (i.e. it has a blank field with NotBlank constraint on it) will raise the error as  expected. This is what i've used:

```php
/**
 * {@inheritdoc}
 */
public function getFormBuilder()
{
    if (isset($this->formOptions['cascade_validation'])) {
        unset($this->formOptions['cascade_validation']);
        $this->formOptions['constraints'][] = new Valid();
    }

    return parent::getFormBuilder();
}
```

**Comment by greg0ire** [comment]
Great! I'll use your solution then. I still don't think the condition is useful though.

**Comment by gremo** [comment]
@greg0ire one could override the admin and `$this->formOptions` thus disabling the cascade validation entirely. The patch should not blindly cascade the validation.

**Comment by greg0ire** [comment]
Oh ok I get it now… I'll use your solution, it's indeed better.
