### ISSUE TITLE
Add missing dependency "nelmio/api-doc-bundle" to composer.json

### ISSUE THREAD

**Issue by andreasschacht** [sonata-project/SonataClassificationBundle#258]
Hi there,

since the controllers (e.g. Api/CategoryController) using the ApiDoc-annotation from the Nelmio\ApiDocBundle, this dependency should be consider in the composer.json

**Comment by greg0ire** [comment]
Hello!

The api is an optional feature, that's why this dependency was not explicitly expressed.

**Comment by andreasschacht** [comment]
Okay,

thanks for answering so fast. Just for your interest, the missing dependency breaks the cache:warmup command, which is part of my deployment process.

**Comment by greg0ire** [comment]
Interesting… are you using the api in your project or not?

**Comment by andreasschacht** [comment]
i don't import the api-routes in the project. Or is there a configuration flag or something to turn it off?

**Comment by greg0ire** [comment]
> Or is there a configuration flag or something to turn it off?

I don't think so, but having one would indeed be great.

**Comment by greg0ire** [comment]
Could you please post a stack trace showing the issue? You can get it with `app/console cache:warmup -vvv`.

**Comment by greg0ire** [comment]
Also, do you still get the error when removing [this file](https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/Resources/config/routing/api.xml) ? Because if not, the right fix would be to find a way to load it conditionally.

**Comment by andreasschacht** [comment]
For some reason I can't reproduce the error on my local machine..., maybe it was an (op)-cache problem on the server. I try to figure it out!

**Comment by greg0ire** [comment]
I've seen strange things happen with / without the `-vvv` flag, maybe you can try without?

**Comment by andreasschacht** [comment]
Like with -vvv flag, on my local machine all works as expected. I try to figure out the problem on the other machine

**Comment by greg0ire** [comment]
Ok… maybe it's related to `--env=prod` ?

**Comment by andreasschacht** [comment]
Okay, can reproduce this behaviour!
I optimized the autoloader with:

`composer install -o`

Then:

`app/console --no-debug cache:warmup -vvv`

Got output:

`// Clearing the cache for the dev environment with debug false                                                         

 // Warming up cache...                                                                                                 


                                                                                                                                                                                                                          
  [Doctrine\Common\Annotations\AnnotationException]                                                                                                                                                                       
  [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\ClassificationBundle\Controller\Api\CategoryController::getCategoriesAction() does not exist, or could not be auto-loaded.  
                                                                                                                                                                                                                          

Exception trace:
 () at /tmp/vagrant-cache/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
 Doctrine\Common\Annotations\AnnotationException::semanticalError() at /tmp/vagrant-cache/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:730
 Doctrine\Common\Annotations\DocParser->Annotation() at /tmp/vagrant-cache/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:663
 Doctrine\Common\Annotations\DocParser->Annotations() at /tmp/vagrant-cache/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:354
 Doctrine\Common\Annotations\DocParser->parse() at /tmp/vagrant-cache/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php:282
 Doctrine\Common\Annotations\AnnotationReader->getMethodAnnotations() at /tmp/vagrant-cache/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php:147
 Doctrine\Common\Annotations\CachedReader->getMethodAnnotations() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php:108
 Symfony\Bundle\FrameworkBundle\CacheWarmer\AnnotationsCacheWarmer->readAllComponents() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/AnnotationsCacheWarmer.php:75
 Symfony\Bundle\FrameworkBundle\CacheWarmer\AnnotationsCacheWarmer->warmUp() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:144
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:96
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:852
 Symfony\Component\Console\Application->doRunCommand() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /tmp/vagrant-cache/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /var/www/main/app/console:30
`

**Comment by greg0ire** [comment]
What if you remove the api.xml file? Is it better?

**Comment by andreasschacht** [comment]
No, it's the same.

**Comment by greg0ire** [comment]
Next step would be to figure out how Symfony looks for annotation when warming its cache.

**Comment by daichihaji** [comment]
I have bumped into the same problem.


 // Warming up the cache for the dev environment with debug false                                                       


```
                                                                                                                                       
  [Doctrine\Common\Annotations\AnnotationException]                                                                                    
  [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method Sonata\MediaBundle\Controller\Api\GalleryContr  
  oller::getGalleriesAction() does not exist, or could not be auto-loaded.                                                             
                                                                                                                                       

Exception trace:
 () at /Users/daichi/CodingWorks/httproot/arserver/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
 Doctrine\Common\Annotations\AnnotationException::semanticalError() at /Users/daichi/CodingWorks/httproot/arserver/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:730
 Doctrine\Common\Annotations\DocParser->Annotation() at /Users/daichi/CodingWorks/httproot/arserver/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:663
 Doctrine\Common\Annotations\DocParser->Annotations() at /Users/daichi/CodingWorks/httproot/arserver/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:354
 Doctrine\Common\Annotations\DocParser->parse() at /Users/daichi/CodingWorks/httproot/arserver/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php:282
 Doctrine\Common\Annotations\AnnotationReader->getMethodAnnotations() at /Users/daichi/CodingWorks/httproot/arserver/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/CachedReader.php:147
 Doctrine\Common\Annotations\CachedReader->getMethodAnnotations() at /Users/daichi/CodingWorks/httproot/arserver/vendor/jms/di-extra-bundle/Metadata/Driver/AnnotationDriver.php:163
 JMS\DiExtraBundle\Metadata\Driver\AnnotationDriver->loadMetadataForClass() at /Users/daichi/CodingWorks/httproot/arserver/vendor/jms/metadata/src/Metadata/Driver/LazyLoadingDriver.php:23
 Metadata\Driver\LazyLoadingDriver->loadMetadataForClass() at /Users/daichi/CodingWorks/httproot/arserver/vendor/jms/metadata/src/Metadata/MetadataFactory.php:103
 Metadata\MetadataFactory->getMetadataForClass() at /Users/daichi/CodingWorks/httproot/arserver/vendor/jms/di-extra-bundle/HttpKernel/ControllerResolver.php:98
 JMS\DiExtraBundle\HttpKernel\ControllerResolver->createInjector() at /Users/daichi/CodingWorks/httproot/arserver/vendor/jms/di-extra-bundle/HttpKernel/ControllerInjectorsWarmer.php:37
 JMS\DiExtraBundle\HttpKernel\ControllerInjectorsWarmer->warmUp() at /Users/daichi/CodingWorks/httproot/arserver/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /Users/daichi/CodingWorks/httproot/arserver/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheWarmupCommand.php:68
 Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand->execute() at /Users/daichi/CodingWorks/httproot/arserver/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /Users/daichi/CodingWorks/httproot/arserver/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:866
 Symfony\Component\Console\Application->doRunCommand() at /Users/daichi/CodingWorks/httproot/arserver/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /Users/daichi/CodingWorks/httproot/arserver/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/daichi/CodingWorks/httproot/arserver/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /Users/daichi/CodingWorks/httproot/arserver/app/console:22

```

**Comment by jordisala1991** [comment]
This is not a problem on Sonata side, but a problem with JMSDiExtraBundle.

I think it was solved at some point, and we added some code on admin-bundle too.

Linking a few PR and issues:

https://github.com/sonata-project/SonataAdminBundle/issues/4292
https://github.com/sonata-project/SonataAdminBundle/pull/4320
https://github.com/sonata-project/SonataAdminBundle/pull/4312

Closing for now
