### ISSUE TITLE
New stable release with Symfony 3 compatibility?

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataClassificationBundle#263]
It would be great a new stable release with Symfony 3 compatibility #250  and other critical fixes like #255.

**Comment by greg0ire** [comment]
Asking @Soullivaneuh right now!

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/SonataClassificationBundle/releases/tag/3.2.0

And happy new year. :tada:
