### ISSUE TITLE
SonateMediaBundle integration. error: "There is no main category related to context: default"

### ISSUE THREAD

**Issue by SergeyMilegov** [sonata-project/SonataClassificationBundle#276]
https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Listener/ORM/MediaEventSubscriber.php#L93
https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Model/Media.php#L86
https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/Entity/CategoryManager.php#L132

You try to compare int "id" with string "context". How it should work?

**Comment by ZRazor** [comment]
Try to run following commands:
```
bin/console sonata:classification:fix-context
bin/console sonata:media:fix-media-context
```

**Comment by pascal-splotches** [comment]
At multiple locations it is implied that the id of a Context should be a string. But it is loaded into the `$rootCategories` array with a numerical id.

[/Command/FixContextCommand.php:49](https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/Command/FixContextCommand.php#L49)
```php
$defaultContext->setId(ContextInterface::DEFAULT_CONTEXT); // ContextInterface::DEFAULT_CONTEXT is a string
```

[/Listener/ORM/MediaEventSubscriber.php:96](https://github.com/sonata-project/SonataMediaBundle/blob/3.x/Listener/ORM/MediaEventSubscriber.php#L96)
```php
return $this->rootCategories[$media->getContext()]; // $media->getContext() is a string
```

[/Entity/CategoryManager.php:132](https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/Entity/CategoryManager.php#L132)
```php
$categories[$category->getContext()->getId()] = $loadChildren ? $this->getRootCategory($category->getContext()) : $category; // $category->getContext()->getId() is an integer
```

**Comment by pascal-splotches** [comment]
Further testing shows that id does indeed have to be set to string for the Context entity.

Make sure that in your easy-extends of the `ClassificationBundle` the `id` is set to string:
```yaml
ClassificationBundle\Entity\Context:
    type: entity
    table: classification_context

    id:
        id:
            type: string

            generator:
                strategy: NONE
```

**Comment by idhard** [comment]
i had similar issue , setting the id to string solved it , thanks

**Comment by mauriau** [comment]
Hi, I got the same issue, but I ever set generator to none in entity configuration, nothing change :/

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
