### ISSUE TITLE
SonataDatagridBundle 2.2.1 make tests fail.

### ISSUE THREAD

**Issue by jlamur** [sonata-project/SonataClassificationBundle#277]
The release of the 2.2.1 version of SonataDatagridBundle, 6 days ago, makes tests fail.

Example on Travis: https://travis-ci.org/sonata-project/SonataClassificationBundle/builds/201959001

@greg0ire I think it's your [commit (PR #45) on SonataDatagridBundle](https://github.com/sonata-project/SonataDatagridBundle/pull/45) that makes tests fail.

**Comment by greg0ire** [comment]
This has been fixed… was it on another repo?

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataPageBundle/pull/783#issuecomment-279437438

**Comment by greg0ire** [comment]
Can you please make a PR to fix that for this bundle?

**Comment by jlamur** [comment]
@greg0ire Yup :)

**Comment by greg0ire** [comment]
@jlamur looks like @jordisala1991 was faster :P
