### ISSUE TITLE
Datagrid filter conflicts with context parameter

### ISSUE THREAD

**Issue by ZRazor** [sonata-project/SonataClassificationBundle#286]
## Subject

Datagrid filter conflicts with context parameter.

## Steps to reproduce

For example we have 2 contexts: `default` and `context`.

When first entering the categories in the admin panel, the uri looks like:
`tree?hide_context=0`

We can switch contexts in categories context custom switcher
<img width="288" alt="2017-03-03 10 00 08" src="https://cloud.githubusercontent.com/assets/1560126/23532669/593a624c-fff8-11e6-8c2b-0fc5fa972b62.png">

If we switch to `default` context, the uri will look like this:
`tree?context=default&hide_context=0`

And the datagrid filter will appear with the selected context:
<img width="505" alt="2017-03-03 10 21 07" src="https://cloud.githubusercontent.com/assets/1560126/23533370/1d7a48ee-fffd-11e6-8531-c2dd93158c75.png">

If we select `context` context in datagrid filter and press "Filter", we will have uri:
`
list?filter[context][type]=&filter[context][value]=context&filter[name][type]=&filter[name][value]=&filter[enabled][type]=&filter[enabled][value]=&filter[_page]=1&filter[_sort_by]=id&filter[_sort_order]=ASC&filter[_per_page]=32&context=default&hide_context=0
`

Now we have `filter[context][value]=context` from the selected filter and `context=default`, which priority is higher.

## Expected results

We are in a tree mode with selected `context` context.

## Actual results

We are in a list mode with selected `default` context. Does not matter what is in the uri param `filter[context][value]`, filter will be set to `default` context, which is defined in `context=default` parameter. 
Now we can try to change context in datagrid filter, but it would be locked on `default` because of 
`context=default` parameter. 

If we remove `context=default` from uri, datagrid filter will work fine.

## Checked on
- last 3.x version and datagrid bundle 2.2.1
- 3.2.0 version and datagrid bundle 2.2.0

**Comment by ZRazor** [comment]
Also in tree mode with context parameter (when datagrid filter appears)
`context=default&hide_context=0` we have a form (sonata_type_filter_default) error  in `context` field.
I take a look at it: 
in tree mode normalized format of this field looks like:
`[value => Object(Application\Sonata\ClassificationBundle\Entity\Context)]`
in list mode (where are no errors):
`[type => null, value => Object(Application\Sonata\ClassificationBundle\Entity\Context)]`

Conclusion:
`type` is missing.

**Comment by jordisala1991** [comment]
This one is already fixed and it will be on next release. Closing

**Comment by ZRazor** [comment]
@jordisala1991, are you sure that the whole issue is fixed?
In my last PR i only fixed a form error, not parameters conflict.
I was planning to provide another PR for this issue.
