### ISSUE TITLE
Restrict by context on Category List view

### ISSUE THREAD

**Issue by Adraesh** [sonata-project/SonataClassificationBundle#291]
Hi guys,

I would like to restrict and display only categories from one given context when calling the category popup choices from a sonata_type_model_list, bellow the filed's code:

```
->add('articleCategory', 'sonata_type_model_list', array(
                        'label' => 'Catégorie',
                        'by_reference' => false,
                        'required' => true,
                    ), array(
                        'link_parameters' => array(
                            'context' => 'articles',
                            'hide_context' => true,
                        )
                    ))
```
The link generated well includes my context=articles&hide_context=true as u can see here: /admin/sonata/classification/category/list?context=articles&hide_context=1

As you can see bellow on my screenshot, the popin opens and still display all the Categories...:
![screen shot 2017-03-10 at 6 46 12 pm](https://cloud.githubusercontent.com/assets/3873988/23804550/fe9aa5c4-05c2-11e7-9041-e1a52a017c2c.png)

Someone has an idea ?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

**Comment by Adraesh** [comment]
Alright, but I already check and re-recheck everywhere without finding any answer.

**Comment by greg0ire** [comment]
You can ask question on SO, you're not forced to use it in read-only mode.

**Comment by Adraesh** [comment]
@greg0ire It's not like I am trying to find an answer since some minutes. I am looking for it since severals days without finding any clue, that's why I came here because I though it was an issue. Sorry to bother you.

**Comment by greg0ire** [comment]
> It's not like I am trying to find an answer since some minutes.

We didn't mean to imply that you did not do your due diligence, and we don't care how long you searched. If you have a *question*, please ask it on SO. If you are completely sure you found a bug, or that a feature is missing, then and only then take it here. We believe it's for the best, please do as we ask.
