### ISSUE TITLE
How to add Category to anything with Form\Type\CategorySelectorType

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataClassificationBundle#320]
Documentation should include this. I was playing with the category system and finally got it working so that the tree view is displayed in the selection of the category. I didn't find a good example on this anywhere so heres what i did:

CLASS:
```
class Item
{
...
    /**
     * @ORM\ManyToOne(targetEntity="Application\Sonata\ClassificationBundle\Entity\Category", cascade={"persist"})
     * @ORM\JoinTable(
     *      name="Item_category",
     *      joinColumns={@ORM\JoinColumn(name="item_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="category_id", referencedColumnName="id")}
     * )
     */
    private $category;

```

ADMIN
```
use Application\Sonata\ClassificationBundle\Entity\Category;
...
    protected function configureFormFields(FormMapper $formMapper)
    {
             $context = 'default'; 
             ->add('category', 'Sonata\ClassificationBundle\Form\Type\CategorySelectorType', array(
                        'class' => $this->getConfigurationPool()->getAdminByAdminCode('sonata.classification.admin.category')->getClass(),
                        'required' => false,
                        'by_reference' => false,
                        'context' =>  $this->getConfigurationPool()->getContainer()->get('sonata.classification.manager.context')->find($context);
                        'model_manager' => $this->getConfigurationPool()->getAdminByAdminCode('sonata.classification.admin.category')->getModelManager(),
                        'category' => $this->getSubject()->getCategory() ? $this->getSubject()->getCategory() : new Category,
                        'placeholder' => $this->getSubject()->getCategory(),
                        'btn_add' => false
                    ))
```

Is this how it should be done?

**Comment by greg0ire** [comment]
@enekochan @ZRazor , I think you might be able to help?
@haivala can you contribute to the docs? Maybe your solution is not perfect, but if it works...

**Comment by haivala** [comment]
Yea. It's not perfect. It's just working example.

What this still needs is how to configure the same tree view in admins DatagridFilters..

**Comment by enekochan** [comment]
I was actually needing this for a Category select in an admin class this week! Thanks! I'll try to look at this again soon because I also need a Category select in the frontend but with some customization (first level categories should not be able to be selected), not sure when I'll have time though.

BTW the `childWalker` function in `CategorySelectorType` looks like it's adding an extra dash character for sublevels. It's a very simple fix so if that's the case I can provide a PR.

![screen shot 2017-08-19 at 20 51 40](https://user-images.githubusercontent.com/1836845/29489389-64321318-8520-11e7-9a22-aa145edc37d0.png)

**Comment by haivala** [comment]
I'm still waiting for input..

**Comment by haivala** [comment]
asking again:
@enekochan @ZRazor , I think you might be able to help? Is this how it should be done?

**Comment by ZRazor** [comment]
I suppose that for now it can be done this way:
```php
    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Category")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    protected $category;
```

```php
   ->add('category', CategorySelectorType::class, [
        'label' => 'product.category',
        'class' => 'AppBundle\Entity\Category',
        'required' => false,
        'by_reference' => false,
        'context' =>  'default',
        'model_manager' => $this->getConfigurationPool()->getAdminByAdminCode('sonata.classification.admin.category')->getModelManager(),
        'category' => $this->getConfigurationPool()->getContainer()->get('sonata.classification.manager.category')->getRootCategory(),
        'btn_add' => false
    ])
```
If you want to display all categories in all contexts, than dont pass `context` param.

`AppBundle\Entity\Category` - extension from `Sonata\ClassificationBundle\Entity\BaseCategory`

**Comment by haivala** [comment]
Thank you!
Do you know how to configure the same tree view in admins DatagridFilters?
After that this would be complete recipe for documentation?

**Comment by ZRazor** [comment]
For datagrid:
```php
    public function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter
            ->add('category',  'doctrine_orm_choice', [
                    'label' => 'product.category'
                ], CategorySelectorType::class,  [
                    'class' => 'AppBundle\Entity\Category',
                    'context' =>  'default',
                    'model_manager' => $this->getConfigurationPool()->getAdminByAdminCode('sonata.classification.admin.category')->getModelManager(),
                    'category' => new Category(),
                ]
            )
            ...
```

**Comment by ZRazor** [comment]
@haivala If there are no more suggestions, I think this can go for recipes

**Comment by haivala** [comment]
How about removing that check in `CategorySelectorType`?

If I add 'multiple' => true in the filter it does not work..

**Comment by ZRazor** [comment]
@haivala 
I have tried this way and it works as it is:
```php
    public function configureDatagridFilters(DatagridMapper $filter)
    {
        $filter
            ->add('category',  null, [
                    'label' => 'product.category'
                ], CategorySelectorType::class,  [
                    'class' => 'AppBundle\Entity\Category',
                    'context' =>  'default',
                    'model_manager' => $this->getConfigurationPool()->getAdminByAdminCode('sonata.classification.admin.category')->getModelManager(),
                    'category' => new Category(),
                    'multiple' => true,
                ]
            )
            ...
```

**Comment by lracicot** [comment]
It's not obvious in the documentation, but the classification bundle depends on the media bundle because of this: https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/src/Model/Category.php#L16

```
use Sonata\MediaBundle\Model\MediaInterface;
``` 

That's kind of a problem for me, because I don't need to use the media bundle and I don't need images on categories.

**Comment by haivala** [comment]
I'm still using this and it really should be documented but I don't have the time..
