### ISSUE TITLE
Error while run easy-extends command: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "JsonType" from namespace "Sonata\Doctrine\Types".

### ISSUE THREAD

**Issue by apoorva-shah** [sonata-project/SonataClassificationBundle#326]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.23.0 3.23.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/classification-bundle     3.3.1  3.3.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.4.0  3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.6  3.1.6  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  1.7.1  Lightweight Exporter library

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.1.0 v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.8 v3.3.8 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0 v1.5.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0 v1.5.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0 v1.5.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0 v1.5.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0 v1.5.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0 v1.5.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3 v3.0.3 Symfony SwiftmailerBundle
symfony/symfony            v3.3.8 v3.3.8 The Symfony PHP framework

```

#### PHP version

```
$ php -v
# PHP 7.0.23-1+ubuntu14.04.1+deb.sury.org+1
```

## Composer require composer require sonata-project/classification-bundle

Error while run easy-extends command: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "JsonType" from namespace "Sonata\Doctrine\Types".

## Steps to reproduce
I install fresh symfony and install sonata classification bundle. after configuration from here 
https://sonata-project.org/bundles/classification/2-x/doc/reference/installation.html i got error.

## See file attached.
[sonata_classification.txt](https://github.com/sonata-project/SonataClassificationBundle/files/1284837/sonata_classification.txt)

## Actual results

`admin@nlspc-33:/var/www/html/sym_sylius$ php bin/console sonata:easy-extends:generate --dest=src SonataClassificationBundle
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "JsonType" from namespace "Sonata\Doctrine\Types".
Did you forget a "use" statement for another namespace? in /var/www/html/sym_sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php:174
Stack trace:
#0 /var/www/html/sym_sylius/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(68): Doctrine\DBAL\Types\Type::getType('json')
#1 /var/www/html/sym_sylius/var/cache/dev/appDevDebugProjectContainer.php(859): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /var/www/html/sym_sylius/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(335): appDevDebugProjectContainer->getDoctrine_Dbal_DefaultConnectionService()
#3 /var/www/html/sym_sylius/var/cache/dev/appDevDebugProjectContainer.php(900): Symfony\Component\DependencyInjection\Container->get('doctrine.dbal.d...') in /var/www/html/sym_sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/Type.php on line 174
`

![sonata-classification-bundle-error](https://user-images.githubusercontent.com/24920542/30197489-b013797e-9485-11e7-9f13-25f7026ab946.png)

**Comment by patrickvale** [comment]
I also encountered this. It seems there is a [Sonata Doctrine Extensions](https://github.com/sonata-project/sonata-doctrine-extensions) package, which is also required.

`composer require sonata-project/doctrine-extensions`

fixed this for me.

**Comment by jordisala1991** [comment]
You need to follow Sonata 3 installation guide for the versions you are using. ClassificationBundle does not need by itself the JsonType (other sonata bundles might require it)
