### ISSUE TITLE
Context is required when creating a tag, but this isn't enforced at database level

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataClassificationBundle#366]
As per validation rules ([validation.xml](https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/src/Resources/config/validation.xml#L22)) a tag cannot be created without a context. This is not enforced at database level (foreign key can be null).

Should we make the column `NOT NULL` and add a `ON DELETE CASCADE` behaviour on it (currently is `RESTRICT` see https://github.com/sonata-project/SonataClassificationBundle/issues/361)?

**Comment by OskarStark** [comment]
@core23 can you please share your opinion here? IMO you are the guy who knows most about this bundle 😄

**Comment by gremo** [comment]
Let me elaborate more on this. I said that this bundle is a "mess" in the sense that I can't understand some choices made in the past (I'm using sonata bundles since a few months):

The context property for Tag and Collection entites **is nullable**. However:

- Validation constraints won't allow to create a tag or a collection without a context (see [validation.xml](https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/src/Resources/config/validation.xml))
- The **behaviour for a the associaction join column is `RESTRICT`** (see [SonataClassificationExtension.php](https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/src/DependencyInjection/SonataClassificationExtension.php#L166)) that means that you can even delete a context from the database if a tag or collection exists

What does this means? No one right now should have a tag or collection without a context (with `NULL` in the context column)!

That said:
- We should merge #367, #368
- We should merge #360 and automatically create a context
- We should remove the FixContextCommand command (or at least remove the useless parts)

**Comment by OskarStark** [comment]
thanks for the detailed feedback @gremo 

@rande can you give your thoughts on this?

**Comment by gremo** [comment]
Closed in favour of https://github.com/sonata-project/SonataClassificationBundle/issues/386
