### ISSUE TITLE
Associations inconsistency for tag, collection and category towards context

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataClassificationBundle#386]
I'm creating this issue as an explanation about my upcoming PR.

**Fact 1**: as per validation rules, a **tag cannot be created without a context**.

https://github.com/sonata-project/SonataClassificationBundle/blob/d189426c05ed3fa5def926cd0f24c34585439cfa/src/Resources/config/validation.xml#L20-L22

However:
1. This is not enforced at database level because the foreign key _can_ be null.
2. The current foreign key behavior is `RESTRICT`, that means that a context can't be deleted if a tag is associated to that context. When you try to delete a context already associated to a tag an exception is thrown (at database level).

**Proposal 1**: make the `context` column `NOT NULL` and add the behavior `ON DELETE CASCADE`, because no one should have a tag or collection without a context (at least, using the admin).

**Fact 2**: same as fact 1, but for **collection**.
**Proposal 2**: same as proposal 1.

**Fact 3**: when you create a  category, **a context is always associated to that category** (but pay attention to the point 2).

https://github.com/sonata-project/SonataClassificationBundle/blob/d189426c05ed3fa5def926cd0f24c34585439cfa/src/Admin/ContextAwareAdmin.php#L46-L51

However:
1. The current foreign key behavior is `RESTRICT`, that means that a context can't be deleted if a category is associated to that context.
2. If there are no categories at all, the context parameter is absent and the context isn't created nor associated with the category. Thus, after adding a new root category (which is missing the context), an exception is thrown when browsing category tree, because of this check:

https://github.com/sonata-project/SonataClassificationBundle/blob/d189426c05ed3fa5def926cd0f24c34585439cfa/src/Entity/CategoryManager.php#L175-L177

**Proposal 3**:  make the `context` column `NOT NULL` and add the behaviour `ON DELETE CASCADE`; always create a context in `ContextAwareAdmin::getNewInstance()` even if the context parameter is missing.

**Bonus point**: the `sonata:classification:fix-context` command can be deleted because we create context and always assign a context to tags, collections and categories using the admin.

**Comment by gremo** [comment]
@core23 @greg0ire do you think this is right? I can work on a PR...

**Comment by greg0ire** [comment]
This sounds right and I wonder why it was not done like you described from the start…
