### ISSUE TITLE
Document manager classes does not respect PageableManagerInterface

### ISSUE THREAD

**Issue by Wharenn** [sonata-project/SonataClassificationBundle#39]
Methods getPager of these classes does not respect the signature introduced by PageableManagerInterface : 
- Sonata\ClassificationBundle\Document\CategoryManager
- Sonata\ClassificationBundle\Document\CollectionManager
- Sonata\ClassificationBundle\Document\TagManager

**Comment by liquorvicar** [comment]
Note the PR above only fixes the TagManager. There are still issues with the CollectionManager and the categoryManager.
