### ISSUE TITLE
sonata-project/classification-bundle 4.x-dev requires sonata-project/admin-bundle ^3.31

### ISSUE THREAD

**Issue by desmax** [sonata-project/SonataClassificationBundle#395]
I wanted to start upgrading  to Symfony 4, that means using master branch of Admin bundle,  but I get this error: `sonata-project/classification-bundle 4.x-dev requires sonata-project/admin-bundle ^3.31`, can dependencies be updated?

**Comment by kunicmarko20** [comment]
You don't have to use master branches, sonata stable still works with symfony4.
