### ISSUE TITLE
Undefined index: parent in vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php line 64 

### ISSUE THREAD

**Issue by kabudu** [sonata-project/SonataClassificationBundle#40]
I was trying to access the classification/category/list page in the Sonata admin area and got the following error:

```
Notice: Undefined index: parent in /var/www/project/vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php line 64
```

It appears that the problem is because the field "parent" is not defined in any of the doctrine entity configuration files, even though it is defined as a property in the Model class Sonata\ClassificationBundle\Model\Category. What I would like to know is whether this was an over-sight or it is by design.

One solution would be to add a definition for the "parent" field in the extended bundle entity configuration file which will subsequently create a column in the database for the category table. Seeing as I don't know how it was designed to work, I want to know if that is the right solution for solving this problem.

**Comment by jasperdcbe** [comment]
The "Impossible to invoke a method ("id") on a NULL variable ("") in SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig at line 60" is probably caused because you also have the media bundle loaded but not properly configured.

If you modify "\Sonata\ClassificationBundle\Admin\CategoryAdmin::configureFormFields" and comment out the code within the if statement that checks whether "Sonata\MediaBundle\Model\MediaInterface" exists or not the problem should be solved. I'm not sure how to fix it though.

**Comment by EnoahNetzach** [comment]
@jasperdcbe yes, that seems to be the case.
The only thing I can't get right is the "media bundle loaded but not properly configured" part. I'm quite sure it's configured, but still it doesn't work..

**Comment by sylzys** [comment]
Same bug here :/
Notice: Undefined index: parent on in vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php at line 64
when trying to access classification/category/list

**Comment by 3mg** [comment]
I had the same issue. It solved by adding SonataEasyExtendsBundle to AppKernel, and updating schema.

new Sonata\EasyExtendsBundle\SonataEasyExtendsBundle(),

**Comment by SergeyMilegov** [comment]
The configs for joining tables are in SonataClassificationExtension.
[https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/DependencyInjection/SonataClassificationExtension.php#L109](https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/DependencyInjection/SonataClassificationExtension.php#L109)
So you have to add to config if classes are in your bundle:
sonata_classification:
    class:
        category: AppBundle\Entity\Media\Category
        collection: AppBundle\Entity\Media\Collection
        context: AppBundle\Entity\Media\Context
        tag: AppBundle\Entity\Media\Tag
        media: AppBundle\Entity\Media\Media
or create bundle with classes throw SonataEasyExtendsBundle wich will be used by default.

**Comment by jordisala1991** [comment]
Missing or bad config. Closing. Ping me of im wrong and this is a bug on sonata side
