### ISSUE TITLE
Context::__toString() must return a string value

### ISSUE THREAD

**Issue by anegve** [sonata-project/SonataClassificationBundle#472]
The bug was describe in https://github.com/sonata-project/SonataMediaBundle/issues/1629
The reason of bug in https://github.com/sonata-project/SonataMediaBundle/issues/1629#issuecomment-541469552

in file Sonata\ClassificationBundle\Entity\CategoryManager:296
(https://github.com/sonata-project/SonataClassificationBundle/blob/3.x/src/Entity/CategoryManager.php)

```
$context_result = $this->contextManager->find($context); // $context_result = NULL 
// if context's table is empty
```

in file Sonata\ClassificationBundle\Entity\CategoryManager:298
```
if (!$context instanceof ContextInterface) { // true
      $context = $this->contextManager->create(); // $context = object

      $context->setId($context);  // set object in id field
      $context->setName($context); // set object in name field
      $context->setEnabled(true);

      $this->contextManager->save($context);
}
```

**Comment by greg0ire** [comment]
Fixed in https://github.com/sonata-project/SonataClassificationBundle/releases/tag/3.9.1
