### ISSUE TITLE
There is no column with name 'slug' on table 'classification__collection'

### ISSUE THREAD

**Issue by martinfer** [sonata-project/SonataClassificationBundle#56]
Hi,

After updating a symfony2 project with composer I had to update media bundle because It required classification bundle.
So I follow the installation and now I getting  [Doctrine\DBAL\Schema\SchemaException]                                      
  There is no column with name 'slug' on table 'classification__collection'. 

"php": ">=5.3.3",
    "symfony/symfony": "2.5.*",
    "doctrine/orm": "~2.2,>=2.2.3",
    "doctrine/doctrine-bundle": "~1.2",
    "twig/extensions": "1.0.*@dev",
    "symfony/assetic-bundle": "~2.3",
    "symfony/swiftmailer-bundle": "~2.3",
    "symfony/monolog-bundle": "~2.4",
    "sensio/distribution-bundle": "~3.0",
    "sensio/framework-extra-bundle": "~3.0",
    "incenteev/composer-parameter-handler": "~2.0",
    "friendsofsymfony/user-bundle": "~1.3@dev",
    "sonata-project/core-bundle": "dev-master",
    "sonata-project/admin-bundle": "dev-master",
    "sonata-project/doctrine-orm-admin-bundle": "dev-master",
    "sonata-project/easy-extends-bundle": "dev-master",
    "sonata-project/user-bundle": "dev-master",
    "sonata-project/datagrid-bundle": "~2.2@dev",
    "sonata-project/classification-bundle": "~2.3@dev",
    "jms/serializer-bundle": "~0.11",
    "sonata-project/media-bundle": "2.4.*@dev",
    "stof/doctrine-extensions-bundle": "~1.1@dev",
    "knplabs/knp-paginator-bundle": "~2.4",
    "hwi/oauth-bundle": "0.4.*@dev"

**Comment by srascar** [comment]
@martinfer 
You need to enable the SonataClassificationBundle in your doctrine configs:

    // config.yml
    ...
    doctrine:
        orm:
            entity_managers:
                default:
                    mappings:
                        ...
                        SonataClassificationBundle: ~

Otherwize, Doctrine wont be able to map your parent entity mapping.
