### ISSUE TITLE
[Mapping]  FAIL - The entity-class 'Application\Sonata\ClassificationBundle\Entity\Category' mapping is invalid:

### ISSUE THREAD

**Issue by diphda** [sonata-project/SonataClassificationBundle#57]
I got this error 
* The field Application\Sonata\ClassificationBundle\Entity\Category#children is on the inverse side of a bi-directional relationship, but the specified mappedBy association on the target-entity Application\Sonata\ClassificationBundle\Entity\Category#parent does not contain the required 'inversedBy=children' attribute.

maybe is a typo in the SonataClassificationExtension?

$collector->addAssociation($config['class']['category'], 'mapManyToOne', array(
            'fieldName'     => 'parent',
            'targetEntity'  => $config['class']['category'],
            'cascade'       => array(
                'remove',
                'persist',
                'refresh',
                'merge',
                'detach',
            ),
            'mappedBy'      => NULL,
            'inversedBy'    => NULL,                                <==== maybe: 'children' ?
            'joinColumns'   => array(
                array(
                 'name'     => 'parent_id',
                 'referencedColumnName' => 'id',
                 'onDelete' => 'CASCADE',
                ),
            ),
            'orphanRemoval' => false,
        ));

**Comment by cmberlin** [comment]
Got the same error in:
"name": "sonata-project/classification-bundle",
"version": "2.2.1"

Error was gone after setting 'children' to inversedBy prop like @diphda explained already!

**Comment by jmontoyaa** [comment]
You have to add this:

```
sonata_media:
    class:
        category: MyBundle\ClassificationBundle\Entity\Category
```

**Comment by OskarStark** [comment]
this should work, i close this ticket. Feel free to reopen if i missed something

thank you @jmontoyaa
