### ISSUE TITLE
classification-bundle/Controller/CategoryAdminController.php on line 79

### ISSUE THREAD

**Issue by josephzhao** [sonata-project/SonataClassificationBundle#61]
Fatal error: Call to a member function getContext() on a non-object in  /vendor/sonata-project/classification-bundle/Controller/CategoryAdminController.php on line 79

Uncaught PHP Exception RuntimeException: "The first category must be the root" at /NetBeansProjects/COBASV/vendor/sonata-project/classification-bundle/Entity/CategoryManager.php line 211 {"exception":"[object](RuntimeException: The first category must be the root at /NetBeansProjects/COBASV/vendor/sonata-project/classification-bundle/Entity/CategoryManager.php:211)"} []

**Comment by blaues0cke** [comment]
Can confirm that running `sonata:classification:fix-context` followed by adding a first category manually in the database will fix the problems at all.

**Comment by josephzhao** [comment]
Hello All 

because of mysql and postgresql database for index nulls is different:

http://use-the-index-luke.com/sql/sorting-grouping/order-by-asc-desc-nulls-last

so for the CategoryManager.php

   protected function loadCategories(ContextInterface $context)

 $categories = $this->getObjectManager()->createQuery(sprintf('SELECT c, FROM %s c WHERE c.context = :context ORDER BY c.parent is null,c.parent ASC', $class))
             ->setParameter('context', $context->getId())
            ->execute();
$categories will get different sort result, for postgresql last one is parent = NULL


Thanks

Joseph

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataClassificationBundle/pull/101

**Comment by jordisala1991** [comment]
This seems a bad configuration. Should not happen on 3.x fresh install. Closing
