### ISSUE TITLE
Add 'type' field on categories, collections and tags to distinguish the entity they manager

### ISSUE THREAD

**Issue by Bladrak** [sonata-project/SonataClassificationBundle#7]
Thomas,

I was thinking about adding a 'type' field on each of the classification bundle entities in order to easily retrieve for instance the product categories. This would avoid costly joins in queries and algorithm problems (for instance, a parent category without any product wouldn't show up instead of adding another join).

What would you think about that?

**Comment by edouardkombo** [comment]
Hi @Bladrak , did you resolved your problem since?

**Comment by Bladrak** [comment]
Hey @edouardkombo I think that now the context field answers that indeed :) Thanks for bringing that up. I'm closing the issue.

**Comment by edouardkombo** [comment]
Can you explain me please?

**Comment by edouardkombo** [comment]
I do not have contexts, maybe I should update my version.

**Comment by Bladrak** [comment]
Yes indeed, they are present, and they allow you to define what is the category for :)
