### ISSUE TITLE
Context cannot be null in new category creation

### ISSUE THREAD

**Issue by maikelohcfg** [sonata-project/SonataClassificationBundle#74]
When i try to create a new category from sonata admin it throw me this error: Context cannot be null at vendor/sonata-project/classification-bundle/Entity/CategoryManager.php at line 127. I follow the installation instruction and here is my composer.json

"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.5._",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0",
        "sonata-project/admin-bundle": "2.4._@dev",
        "sonata-project/doctrine-orm-admin-bundle": "2.3._@dev",
        "knplabs/knp-paginator-bundle": "2.4._@dev",
        "stof/doctrine-extensions-bundle": "1.2._@dev",
        "raulfraile/ladybug-bundle": "dev-master",
        "sonata-project/user-bundle": "2.3._@dev",
        "sonata-project/datagrid-bundle": "2.2._@dev",
        "sonata-project/ecommerce": "2.3._@dev",
        "sonata-project/news-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "dev-master",
        "sonata-project/classification-bundle": "dev-master",
        "sonata-project/media-bundle": "2.3._@dev",
        "sonata-project/translation-bundle": "2.3._@dev",
        "sonata-project/comment-bundle": "2.2._@dev",
        "jms/serializer-bundle": " 0.13._@dev",
        "sonata-project/intl-bundle": "2.2._@dev",
        "friendsofsymfony/rest-bundle": "1.5._@dev",
        "sonata-project/notification-bundle": "2.3._@dev",
        "sonata-project/page-bundle": "2.3._@dev",
        "symfony-cmf/routing-bundle": "1.3.*@dev",
        "cocur/slugify": "dev-master"
    },

**Comment by divined** [comment]
I got this error with:

"sonata-project/admin-bundle": "^3.35",
"sonata-project/classification-bundle": "^3.7",

---

I created a one category, press save and got this error.
Now i got this error evry time i came to category listing.

```
        "php": "^7.1.3",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "sonata-project/admin-bundle": "^3.35",
        "sonata-project/classification-bundle": "^3.7",
        "sonata-project/doctrine-orm-admin-bundle": "^3.6",
        "sonata-project/easy-extends-bundle": "^2.5",
        "symfony/asset": "^4.1",
        "symfony/console": "^4.1",
        "symfony/expression-language": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/form": "^4.1",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "^4.1",
        "symfony/security-bundle": "^4.1",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/twig-bundle": "^4.1",
        "symfony/validator": "^4.1",
        "symfony/web-link": "^4.1",
        "symfony/webpack-encore-pack": "*",
        "symfony/yaml": "^4.1"

**Comment by divined** [comment]
https://i.imgur.com/FyMquHF.jpg

If i fix context field in the DB, second one have the same problem.

Category add new form did not has a field for context: https://i.imgur.com/FyMquHF.jpg

**Comment by lracicot** [comment]
This is also a problem for me. There seems to be no way to select the context for a new category and it causes the RuntimeException "Context cannot be null" when returning to the list.
