### ISSUE TITLE
[5.x] CategoryAdmin list view does not have edit button because default route is now show

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataClassificationBundle#872]
This is the same thing we did with the PageBundles BlockAdmin.
Was it this? https://github.com/sonata-project/SonataPageBundle/pull/1605

**Comment by VincentLanglet** [comment]
Can you provide a PR ?

**Comment by haivala** [comment]
I'm trying to find bugs first and list them

**Comment by haivala** [comment]
This should be fixed

**Comment by VincentLanglet** [comment]
Pr is welcome
