### ISSUE TITLE
[5.x] CategoryAdmin Tree view is not working

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataClassificationBundle#875]
## Actual results
When I open the admin from SonataAdmin menu I go to
`/admin/app/sonata-sonataclassificationcategory/tree?hide_context=0`
then the default tree view works:
![2022-09-29_104525-area](https://user-images.githubusercontent.com/3918267/192971400-616054dc-a03a-485b-9686-3c276810577a.png)
If I change the category and go to
`/admin/app/sonata-sonataclassificationcategory/tree?context=1&hide_context=0?`
It does not work:
![2022-09-29_104643-area](https://user-images.githubusercontent.com/3918267/192971718-7d4d6f77-47bc-411c-9e23-3d4ccfc9dfcd.png)

**Comment by haivala** [comment]
Does anyone else have this bug?

**Comment by jordisala1991** [comment]
Could you try with a fresh installation using contexts with string id?

I would like to see if it is something related to the wrong docs (already fixed) or if I should invest time on it.

**Comment by jordisala1991** [comment]
Tried to reproduce with #908, and category loads correctly, I think it might be related with the id field of context. Closing for now.

**Comment by haivala** [comment]
Just FYI. I fixed the id field to string and same is still happening. There has to be something else my migration broke. Funny thing is that everything else seems to be working.
