### ISSUE TITLE
getRootCategories of categoryManager is not compartible with SonataMedia bundle

### ISSUE THREAD

**Issue by bardius** [sonata-project/SonataClassificationBundle#96]
Sonata media bundle context field holds a string (that is the name of the context). When the getRootCategories is called the returned categories array has as index the id of the classification context that is mapped to the categories instead, so no matching categories are found for the context of Media Bundle.

To fix this i had to amend line 130 of Entity/Categorymanager to:
$categories[$category->getContext()->getName()] = $loadChildren ? $this->getRootCategory($category->getContext()) : $category;

Replaced the index from $category->getContext()->getId() to $category->getContext()->getName()

**Comment by rande** [comment]
Can you create a PR ? this will be easier to review

Thanks

**Comment by bardius** [comment]
Okay, when i get time I will amend the getRootCategories function to get a second parameter for if it is used by media bundle or not and return the results array mapped by context name in this case
