### ISSUE TITLE
"Position" field in CategoryAdmin only shows "0" all the time

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataClassificationBundle#97]
When I change the value of "position" its saved correctly in the database. But the field only shows "0". Bug or feature?

When I change line 103 in `CategoryAdmin.php` from:

```
->add('position', 'integer', array('required' => false, 'data' => 0))
```

to:

```
->add('position', 'integer', array('required' => false))
```

everything works fine.

![img_239_-_312x216 1](https://cloud.githubusercontent.com/assets/5159398/6749114/5460bcbe-ceed-11e4-8717-49a00ce9b49c.png)

**Comment by core23** [comment]
Have you checked this against the latest stable / master version? @blaues0cke

**Comment by jordisala1991** [comment]
No answer since 2016

Closing as unable to reproduce the issue.
