### ISSUE TITLE
BC Break with 2.3 

### ISSUE THREAD

**Issue by sadortun** [sonata-project/SonataClassificationBundle#99]
Hi,

commit 640f5ce18ac509e3e74802807a48cbf2a606407d break BC for 2.3 LTS in composer.

Please create a 2.3 branch, or revert the change.

```
  Problem 1
    - Installation request for sonata-project/classification-bundle dev-master -> satisfiable by sonata-project/classifi
cation-bundle[dev-master].
    - sonata-project/classification-bundle dev-master requires sonata-project/doctrine-orm-admin-bundle ~2.4@dev -> no m
atching package found.
  Problem 2
    - sonata-project/classification-bundle dev-master requires sonata-project/doctrine-orm-admin-bundle ~2.4@dev -> no m
atching package found.
    - symfony/framework-standard-edition 2.3.x-dev requires sonata-project/classification-bundle dev-master -> satisfiab
le by sonata-project/classification-bundle[dev-master].
    - Installation request for symfony/framework-standard-edition 2.3.x-dev -> satisfiable by symfony/framework-standard
-edition[2.3.x-dev].

```

If you intend to go forwoard by adding a dependency to 2.4, you should create a branch to keep BC 

see https://github.com/sadortun/SonataClassificationBundle/tree/2.3

**Comment by sadortun** [comment]
https://github.com/sadortun/SonataClassificationBundle/tree/2.3

**Comment by mrjingles** [comment]
+1

**Comment by sadortun** [comment]
@OskarStark  Can you merge/create branch '2.3'  from this commit ? 

Thanks

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
